### ISSUE TITLE
Survey Question on the For loop in source file accum_omp.c line 45

### ISSUE THREAD

**Issue by quazirafi** [mogill/ems#33]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions about this for loop:

Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?

How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.

(Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code and see the optimization of parallelization? Yes/No

If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).
The for loop is from line 45 of file 
https://github.com/mogill/ems/blob/master/Tests/accum_omp.c

for (i = 0; i < 100000000; i++)
{
  int retval = __sync_fetch_and_add(&a[i % 3200], 1);
}

**Comment by mogill** [comment]
Hi Quazi,

I can understand how this little piece of code will seem mysteriously pointless.  I don't remember the exact experiment or benchmark, but in that directory there are probably also Python and JS implementations of this loop using EMS for the OpenMP style parallelism and shared memory, and this C w/OMP version was the baseline for comparing performance.

This microbenchmark doesn't even bother to check the results, the print is there just so there's a side effect and the loop doesn't get optimized away.  Another indication this was just used for timing experiments is the size of the array, which looks chosen to fit in L1.

To answer your questions:
- Confidence 5 this program is correct for the purpose of timing the maximum rate of fetch-and-add operations possible, when there is contention contained to the L1 data cache.

- Yes, this loop has measurable benefits from using parallelization.  Indeed, that is the only purpose of the program.

- The program performs a checksum that all the iterations were performed.  The final output is NITER.

If you're curious about how developers parallelize their code, this very repo, EMS, the one this issue is filed against, was created to add OpenMP-like shared memory parallelism to JavaScript and Python.  Over the past 10 years people's response has changed, but still not many users.  Let me know if you'd like to hear more, or go ahead and close the issue if you got what you wanted.  Best regards,

        -J

**Comment by quazirafi** [comment]
Thank you so much for the response. It was really helpful and I am closing this issue. Thanks again!
