### ISSUE TITLE
Survey Question on the For loop in source file Tests/accum_omp.c line 52

### ISSUE THREAD

**Issue by LChenGit** [mogill/ems#34]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions:

1. Have you ever tried to add pragma for that 'for' loop?.

2. How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence.

3. (Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code? Yes/No
- If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).

The for loop is from line 52 of file https:/github.com/mogill/ems/blob/master/Tests/accum_omp.c
Here is a part of the code:

nan
for (i = 0; i < 3200; i++)
{
  sum += a[i];
}

Sincerely thanks

**Comment by mogill** [comment]
Hello again,

1. No, I never tried to turn this into an OMP reduction because the trip count is too short to amortize the parallel overhead
2. High confidence (5) this loop correctly sums the array
3. This program is ephemera captured under revision control, it is not part of a test or example

Please feel free to follow up or close the issue.

           -J

**Comment by LChenGit** [comment]
Thank you @mogill ! I appreciate your feedback. It is important for our research. Thanks again for your time!
